name: Trivy Scan

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  trivy:
    name: Run Trivy Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | \
            sudo tee /etc/apt/trusted.gpg.d/trivy.asc
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | \
            sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y

      - name: Run Trivy on Dockerfile
        run: trivy config --exit-code 1 .

      - name: Run Trivy FS scan
        run: trivy fs --exit-code 1 --severity HIGH,CRITICAL .
